name: deep-audio
channels:
  - conda-forge
dependencies:
  - ffmpeg
  - huggingface_hub
  - jupyter
  - librosa
  - libsndfile
  - matplotlib
  - pandas
  - pip
  - python=3.11
  - python-dotenv
  - transformers
  - pytorch
  - accelerate
  - pyarrow
  - torchaudio
  - pip:
      - funasr
      - modelscope

